schema_version = "1.0.0"
id = "openscatter"
version = "1.0.0"
name = "OpenScatter"
tagline = "OpenScatter is a free and open-source Blender addon for advanced scattering. It's built from the ground up with artists in mind. It includes various features to simulate the natural patterns of foliage growth, as well as less realistic features for users who want artistic control."
maintainer = "May3D"
type = "add-on"
website = "https://github.com/GitMay3D/OpenScatter/blob/main/docs/docs.md"
tags = ["3D View"]
blender_version_min = "4.2.0"
license = [
"SPDX:GPL-2.0-or-later",
]