schema_version = "1.0.0"
id = "openscatter"
version = "1.0.0"
name = "OpenScatter"
tagline = "OpenScatter is a free and open-source Blender addon for advanced scattering. It's built from the ground up with artists in mind. "
maintainer = "May3D"
type = "add-on"
website = "https://github.com/GitMay3D/OpenScatter/blob/main/docs/docs.md"
tags = ["3D View"]
blender_version_min = "4.3.0"
license = [
"SPDX:GPL-2.0-or-later",
]