schema_version = "1.0.0"
id = "openscatter"
version = "1.0.4"
name = "OpenScatter"
tagline = "OpenScatter is a free and open-source Blender addon for advanced scattering"
maintainer = "May3D"
type = "add-on"
website = "https://github.com/GitMay3D/OpenScatter"
tags = ["3D View"]
blender_version_min = "4.2.0"
license = [
"SPDX:GPL-2.0-or-later",
]